'use strict';
// Deterministic structural tests for fishing-spot-finder
// Generated by Test Agent - zero LLM calls, pure code checks

let passed = 0;
let failed = 0;
let total = 0;

(function runTests() {

  // Route file: routes/fishing_spots.js
  try {
    const mod = require('../routes/fishing_spots.js');
    if (typeof mod === 'function' || (mod && typeof mod.use === 'function')) {
      passed += 1;
      console.log('PASS: routes/fishing_spots.js exports a valid router/middleware');
    } else {
      failed += 1;
      console.log('FAIL: routes/fishing_spots.js does not export a function or router');
    }
  } catch (err) {
    failed += 1;
    console.log('FAIL: routes/fishing_spots.js cannot be required: ' + err.message);
  }
  total += 1;

  // Route file: routes/spot_reviews.js
  try {
    const mod = require('../routes/spot_reviews.js');
    if (typeof mod === 'function' || (mod && typeof mod.use === 'function')) {
      passed += 1;
      console.log('PASS: routes/spot_reviews.js exports a valid router/middleware');
    } else {
      failed += 1;
      console.log('FAIL: routes/spot_reviews.js does not export a function or router');
    }
  } catch (err) {
    failed += 1;
    console.log('FAIL: routes/spot_reviews.js cannot be required: ' + err.message);
  }
  total += 1;

  // Route file: routes/user_settings.js
  try {
    const mod = require('../routes/user_settings.js');
    if (typeof mod === 'function' || (mod && typeof mod.use === 'function')) {
      passed += 1;
      console.log('PASS: routes/user_settings.js exports a valid router/middleware');
    } else {
      failed += 1;
      console.log('FAIL: routes/user_settings.js does not export a function or router');
    }
  } catch (err) {
    failed += 1;
    console.log('FAIL: routes/user_settings.js cannot be required: ' + err.message);
  }
  total += 1;

  // Route file: routes/users.js
  try {
    const mod = require('../routes/users.js');
    if (typeof mod === 'function' || (mod && typeof mod.use === 'function')) {
      passed += 1;
      console.log('PASS: routes/users.js exports a valid router/middleware');
    } else {
      failed += 1;
      console.log('FAIL: routes/users.js does not export a function or router');
    }
  } catch (err) {
    failed += 1;
    console.log('FAIL: routes/users.js cannot be required: ' + err.message);
  }
  total += 1;

  // server.js wiring check
  try {
    const fs = require('fs');
    const serverSrc = fs.readFileSync(require.resolve('../server.js'), 'utf8');
    const mountedRoutes = [];
    const unmountedRoutes = [];
    ["routes/fishing_spots.js","routes/spot_reviews.js","routes/user_settings.js","routes/users.js"].forEach(function(rf) {
      const name = rf.replace('routes/', '').replace('.js', '');
      if (serverSrc.includes(name)) {
        mountedRoutes.push(rf);
      } else {
        unmountedRoutes.push(rf);
      }
    });
    if (unmountedRoutes.length === 0) {
      passed += 1;
      console.log('PASS: server.js mounts all ' + mountedRoutes.length + ' route files');
    } else {
      failed += 1;
      console.log('FAIL: server.js missing mounts for: ' + unmountedRoutes.join(', '));
    }
  } catch (err) {
    failed += 1;
    console.log('FAIL: server.js cannot be read: ' + err.message);
  }
  total += 1;

  // Page file size: pages/_app.jsx
  try {
    const fs = require('fs');
    const content = fs.readFileSync(require.resolve('../pages/_app.jsx'), 'utf8');
    if (content.length > 100) {
      passed += 1;
      console.log('PASS: pages/_app.jsx has ' + content.length + ' chars');
    } else {
      failed += 1;
      console.log('FAIL: pages/_app.jsx is too small (' + content.length + ' chars)');
    }
  } catch (err) {
    failed += 1;
    console.log('FAIL: pages/_app.jsx cannot be read: ' + err.message);
  }
  total += 1;

  // Page file size: pages/about.jsx
  try {
    const fs = require('fs');
    const content = fs.readFileSync(require.resolve('../pages/about.jsx'), 'utf8');
    if (content.length > 100) {
      passed += 1;
      console.log('PASS: pages/about.jsx has ' + content.length + ' chars');
    } else {
      failed += 1;
      console.log('FAIL: pages/about.jsx is too small (' + content.length + ' chars)');
    }
  } catch (err) {
    failed += 1;
    console.log('FAIL: pages/about.jsx cannot be read: ' + err.message);
  }
  total += 1;

  // Page file size: pages/account/settings.jsx
  try {
    const fs = require('fs');
    const content = fs.readFileSync(require.resolve('../pages/account/settings.jsx'), 'utf8');
    if (content.length > 100) {
      passed += 1;
      console.log('PASS: pages/account/settings.jsx has ' + content.length + ' chars');
    } else {
      failed += 1;
      console.log('FAIL: pages/account/settings.jsx is too small (' + content.length + ' chars)');
    }
  } catch (err) {
    failed += 1;
    console.log('FAIL: pages/account/settings.jsx cannot be read: ' + err.message);
  }
  total += 1;

  // Page file size: pages/index.jsx
  try {
    const fs = require('fs');
    const content = fs.readFileSync(require.resolve('../pages/index.jsx'), 'utf8');
    if (content.length > 100) {
      passed += 1;
      console.log('PASS: pages/index.jsx has ' + content.length + ' chars');
    } else {
      failed += 1;
      console.log('FAIL: pages/index.jsx is too small (' + content.length + ' chars)');
    }
  } catch (err) {
    failed += 1;
    console.log('FAIL: pages/index.jsx cannot be read: ' + err.message);
  }
  total += 1;

  // Page file size: pages/map.jsx
  try {
    const fs = require('fs');
    const content = fs.readFileSync(require.resolve('../pages/map.jsx'), 'utf8');
    if (content.length > 100) {
      passed += 1;
      console.log('PASS: pages/map.jsx has ' + content.length + ' chars');
    } else {
      failed += 1;
      console.log('FAIL: pages/map.jsx is too small (' + content.length + ' chars)');
    }
  } catch (err) {
    failed += 1;
    console.log('FAIL: pages/map.jsx cannot be read: ' + err.message);
  }
  total += 1;

  // Page file size: pages/reports.jsx
  try {
    const fs = require('fs');
    const content = fs.readFileSync(require.resolve('../pages/reports.jsx'), 'utf8');
    if (content.length > 100) {
      passed += 1;
      console.log('PASS: pages/reports.jsx has ' + content.length + ' chars');
    } else {
      failed += 1;
      console.log('FAIL: pages/reports.jsx is too small (' + content.length + ' chars)');
    }
  } catch (err) {
    failed += 1;
    console.log('FAIL: pages/reports.jsx cannot be read: ' + err.message);
  }
  total += 1;

  // Page file size: pages/search.jsx
  try {
    const fs = require('fs');
    const content = fs.readFileSync(require.resolve('../pages/search.jsx'), 'utf8');
    if (content.length > 100) {
      passed += 1;
      console.log('PASS: pages/search.jsx has ' + content.length + ' chars');
    } else {
      failed += 1;
      console.log('FAIL: pages/search.jsx is too small (' + content.length + ' chars)');
    }
  } catch (err) {
    failed += 1;
    console.log('FAIL: pages/search.jsx cannot be read: ' + err.message);
  }
  total += 1;

  // Page file size: pages/spots/[id].jsx
  try {
    const fs = require('fs');
    const content = fs.readFileSync(require.resolve('../pages/spots/[id].jsx'), 'utf8');
    if (content.length > 100) {
      passed += 1;
      console.log('PASS: pages/spots/[id].jsx has ' + content.length + ' chars');
    } else {
      failed += 1;
      console.log('FAIL: pages/spots/[id].jsx is too small (' + content.length + ' chars)');
    }
  } catch (err) {
    failed += 1;
    console.log('FAIL: pages/spots/[id].jsx cannot be read: ' + err.message);
  }
  total += 1;

  // package.json validity
  try {
    const pkg = require('../package.json');
    if (pkg && pkg.name) {
      passed += 1;
      console.log('PASS: package.json is valid with name=' + pkg.name);
    } else {
      failed += 1;
      console.log('FAIL: package.json missing name field');
    }
  } catch (err) {
    failed += 1;
    console.log('FAIL: package.json invalid: ' + err.message);
  }
  total += 1;

  // schema.sql existence
  try {
    const fs = require('fs');
    const schema = fs.readFileSync(require.resolve('../schema.sql'), 'utf8');
    if (schema.length > 50) {
      passed += 1;
      console.log('PASS: schema.sql exists (' + schema.length + ' chars)');
    } else {
      failed += 1;
      console.log('FAIL: schema.sql too small (' + schema.length + ' chars)');
    }
  } catch (err) {
    failed += 1;
    console.log('FAIL: schema.sql not found: ' + err.message);
  }
  total += 1;

  console.log('\n--- Results ---');
  console.log('Total: ' + total + ', Passed: ' + passed + ', Failed: ' + failed);
  process.exitCode = failed > 0 ? 1 : 0;
})();

